drop sequence incremento;

create sequence incremento increment by 1 start with 1;

execute InicializarBD;

execute añadeArticulos('Camisa', 'L', 1, '19,95', 2, 'BLANCO', 'CAMISA, MANGA LARGA, BLANCO', 5);
execute añadeArticulos('Camiseta', 'M', 2, '17,95', 1, 'AZUL', 'CAMISA, MANGA LARGA, AZUL', 2);
--execute añadeArticulos('Pantalón', 'M', 3, '32.95', 3, 'BEIGE', 'CHINO, PANTALÓN BODAS, COMUNION', 5);
execute añadeArticulos('Gorro', 'SIN TALLA', 5, '9,95', 3, 'ROJO', 'GORRO, NAVIDAD, ESTAMPADO', 3);
execute añadeArticulos('Collar', 'SIN TALLA', 5, '14,95', 4, 'SIN COLOR', 'COLLAR, ADORNOS, CUELLO', 4);
execute añadeArticulos('Pantalón', 'XS', 3, '29,95', 1, 'VERDE', 'VAQUERO, VERDE, INFORMAL', 4);
execute añadeArticulos('Bañador', 'M', 5, '13,95', 3, 'MULTICOLOR', 'BAÑADOR, VERANO, PLAYA, PISCINA', 2);
execute añadeArticulos('Deportes', '39 EU', 4, '19,95', 4, 'BLANCO', 'DEPORTES, CORRER, CARRERA', 5);
execute añadeArticulos('Pantalón', 'S', 3, '19,95', 1, 'AZUL', 'VAQUERO, AZUL, COMODO', 4);
execute añadeArticulos('Camiseta', 'X1', 2, '19,95', 1, 'ROJO', 'CAMISA, MANGA LARGA, ROJO', 4);
execute añadeArticulos('Falda', 'M', 6, '19,95', 2, 'VARICOLOR', 'FALDA, VARICOLOR', 4);
execute añadeArticulos('Vestido', 'L', 7, '7,50', 2, 'MORADO', 'VESTIDO LARGO, VARICOLOR', 4);
execute añadeArticulos('Swetter', 'L', 5, '13,50', 4, 'CAFÉ', 'SWETTER, INVIERNO, FRIO', 4);
execute añadeArticulos('Bufanda', 'SIN TALLA', 5, '11,00', 4, 'AMARILLO', 'BUFANDA,INVIERNO, FRIO', 4);
execute añadeArticulos('Swetter', 'L', 5, '16,50', 4, 'BLANCO', 'SWETTER, INVIERNO, FRIO', 4);
execute añadeArticulos('Camiseta', 'M', 2, '10,00', 1, 'BLANCO', 'CAMISA, MANGA LARGA, BLANCO', 4);
execute añadeArticulos('Pantalón', 'S', 3, '49,00', 2, 'NEGRO', 'VAQUERO, NEGRO, COMODO, INFORMAL', 4);


--EXECUTE CREARPEDIDOS(IDPEDIDO, OID_USUARIO);
execute CrearPedidos (1, 1);
execute CrearPedidos (2, 2);
execute CrearPedidos (3, 4);
execute CrearPedidos (4, 1);


--EXECUTE CREARLINEAPEDIDO (IDPEDIDO, IDARTICULO, CANTIDAD);
execute CREARLINEAPEDIDO (1,2, 3);
execute CREARLINEAPEDIDO (1,11, 4);
execute CREARLINEAPEDIDO (2,4, 1);
execute CREARLINEAPEDIDO (3,11, 1);
execute CREARLINEAPEDIDO (3,14, 7);
execute CREARLINEAPEDIDO (4,7, 2);
execute CREARLINEAPEDIDO (4,1, 4);
execute CREARLINEAPEDIDO (4,2, 1);
execute CREARLINEAPEDIDO (4,3, 2);

EXECUTE CONFIRMARPEDIDO(1);
EXECUTE CONFIRMARPEDIDO(2);
EXECUTE CONFIRMARPEDIDO(3);
EXECUTE CONFIRMARPEDIDO(4);

execute CREARDEVOLUCION (3,'Talla incorrecta');
execute CREARDEVOLUCION (2,'Mal estado');



--OID_DEVOLUCION, IDPEDIDO, NUMEROLINEA, CANTIDAD
execute CREARLINEADEVOLUCION (1,3,2,1);
execute CREARLINEADEVOLUCION (2,2,1,1);

EXECUTE CONFIRMARDEVOLUCION (1);
execute CONFIRMARDEVOLUCION (2);

--OID_USUARIO, P_SUELDO, F INICIO, F FIN, TIENDA
EXECUTE AÑADE_EMPLEADOS(1, 900, TO_DATE('2015-03-31', 'YYYY-MM-DD'), NULL, 2);
EXECUTE AÑADE_EMPLEADOS(3, 1100, TO_DATE('2011-05-14', 'YYYY-MM-DD'), SYSDATE, 1);
EXECUTE AÑADE_EMPLEADOS(2, 1000, SYSDATE, NULL, 1);

--AÑADIMOS INFORMACIÓN DE LOS ARTÍCULOS
INSERT INTO PROPORCIONA VALUES(1, 1, 15, 19.95);
INSERT INTO PROPORCIONA VALUES(6, 1, 45, 13.95);
INSERT INTO PROPORCIONA VALUES(11, 3, 32, 7.50);
INSERT INTO PROPORCIONA VALUES(9, 2, 70, 19.95);
INSERT INTO PROPORCIONA VALUES(13, 2, 5, 11.00);


--AÑADIMOS EL STOCK POR TIENDA

INSERT INTO TIENESTOCKEN VALUES(1, 1, 8);
INSERT INTO TIENESTOCKEN VALUES(11, 2, 4);
INSERT INTO TIENESTOCKEN VALUES(10, 3, 32);
INSERT INTO TIENESTOCKEN VALUES(14, 3, 11);
INSERT INTO TIENESTOCKEN VALUES(9, 2, 5);
INSERT INTO TIENESTOCKEN VALUES(15, 2, 25);


SELECT NOMBRE, APELLIDOS FROM USUARIOS NATURAL JOIN EMPLEADOS;
SELECT NOMBRE, IDARTICULO, PRECIO, SECCION FROM ARTICULOS ORDER BY SECCION;
SELECT NOMBRE, IDARTICULO, CANTIDAD FROM PROPORCIONA NATURAL JOIN ARTICULOS;


--MOSTRAMOS AL CLIENTE EN UNA LISTA LOS ARTÍCULOS DE UNA TEMPORADA
SELECT NOMBRE, PRECIO FROM ARTICULOS WHERE TEMPORADA = 4;