CREATE OR REPLACE PROCEDURE MODIFICA_USUARIO(

V_DNI IN USUARIOS.DNI%TYPE,
P_USERNAME IN USUARIOS.NOMBREUSUARIO%TYPE,
V_NOM IN USUARIOS.NOMBRE%TYPE,
V_APE IN USUARIOS.APELLIDOS%TYPE,
V_EMAIL IN USUARIOS.EMAIL%TYPE,
V_TELF IN USUARIOS.TELEFONO%TYPE,
V_DIR IN USUARIOS.DIRECCION%TYPE,
V_PASS IN USUARIOS.CONTRASEÑA%TYPE,
V_FECHA_NAC DATE) IS
BEGIN
  UPDATE Usuarios SET DNI=V_DNI WHERE NombreUsuario=P_USERNAME;
  UPDATE Usuarios SET NOMBRE=V_NOM WHERE NombreUsuario=P_USERNAME;
  UPDATE Usuarios SET APELLIDOS=V_APE WHERE NombreUsuario=P_USERNAME;
  UPDATE Usuarios SET EMAIL=V_EMAIL WHERE NombreUsuario=P_USERNAME;
  UPDATE Usuarios SET TELEFONO=V_TELF WHERE NombreUsuario=P_USERNAME;
  UPDATE Usuarios SET DIRECCION=V_DIR WHERE NombreUsuario=P_USERNAME;
  UPDATE Usuarios SET CONTRASEÑA=V_PASS WHERE NombreUsuario=P_USERNAME;
  UPDATE Usuarios SET FechaNacimiento=V_FECHA_NAC WHERE NombreUsuario=P_USERNAME;
END;

execute modifica_usuario('17476937L', 'Sergio', 'SergioSergio', 'Garrido Domínguez','sergiotb15@gmail.com','644768390','Calle Salto 10', 'Sergio1234', TO_DATE('1997-02-10', 'YYYY-MM-DD'));