create or replace PROCEDURE MODIFICA_USUARIO(
V_NOMBREUSUARIO IN USUARIOS.NOMBREUSUARIO%TYPE,
V_DNI IN USUARIOS.DNI%TYPE,
V_NOM IN USUARIOS.NOMBRE%TYPE,
V_APE IN USUARIOS.APELLIDOS%TYPE,
V_EMAIL IN USUARIOS.EMAIL%TYPE,
V_TELF IN USUARIOS.TELEFONO%TYPE,
V_DIR IN USUARIOS.DIRECCION%TYPE,
V_PASS IN USUARIOS.CONTRASEÑA%TYPE,
V_FECHA_NAC IN USUARIOS.FECHANACIMIENTO%TYPE) IS

OID_User number;

BEGIN

    SELECT OID_USUARIO INTO OID_User FROM USUARIOS WHERE NOMBREUSUARIO = V_NOMBREUSUARIO;

  UPDATE Usuarios SET DNI=V_DNI WHERE OID_USUARIO = OID_User;
  UPDATE Usuarios SET NOMBRE=V_NOM WHERE OID_USUARIO = OID_User;
  UPDATE Usuarios SET APELLIDOS=V_APE WHERE OID_USUARIO = OID_User;
  UPDATE Usuarios SET EMAIL=V_EMAIL WHERE OID_USUARIO=OID_User;
  UPDATE Usuarios SET TELEFONO=V_TELF WHERE OID_USUARIO=OID_User;
  UPDATE Usuarios SET DIRECCION=V_DIR WHERE OID_USUARIO=OID_User;
  UPDATE Usuarios SET CONTRASEÑA=V_PASS WHERE OID_USUARIO=OID_User;
  UPDATE Usuarios SET FechaNacimiento=V_FECHA_NAC WHERE OID_USUARIO=OID_User;

END;
